#pragma once

#define FRAME_CB_REGISTER b0
#define LIGHTS_CB_REGISTER b1
#define OBJECT_CB_REGISTER b2
#define MATERIAL_CB_REGISTER b3
#define TERRAIN_CB_REGISTER b4
#define META_MESH_CB_REGISTER b5
#define SKY_MESH_CB_REGISTER b6
#define WATER_CB_REGISTER b7
#define THUMBNAIL_CAMERA_CB_REGISTER b8
#define GRID_OVERLAY_CB_REGISTER b9
#define GIZMO_CONE_CB_REGISTER b10

#define TERRAIN_PATCH_DATA_REGISTER t0
#define META_DRAW_INSTANCE_DATA_REGISTER t1
#define WATER_PATCH_DATA_REGISTER t2
