#pragma once

#define FRAME_CB_REGISTER b0
#define LIGHTS_CB_REGISTER b1
#define OBJECT_CB_REGISTER b2
#define MATERIAL_CB_REGISTER b3
#define TERRAIN_CB_REGISTER b4
#define META_MESH_CB_REGISTER b5

#define TERRAIN_PATCH_DATA_REGISTER t0
#define META_DRAW_INSTANCE_DATA_REGISTER t1
